version: "3.7"

services:
  worker:
    # build the image from the Dockerfile in the current directory
    build:
      context: .
      args:
        FLAMENCO_VERSION: "3.2"
        BLENDER_VERSION: "3.3.6"
        BLENDER_MAJOR_MINOR: "3.3"
    command: flamenco-worker
    image: flamenco-worker:latest
    container_name: flamenco-worker
    volumes:
    # Mount the configuration file from the current directory
      - ./build/flamenco-worker.yaml:/flamenco/flamenco-worker.yaml
    ports:
      - "780:8080"