version: "3.7"

services:
  manager:
    # build the image from the Dockerfile in the current directory
    build:
      context: .
      args:
        FLAMENCO_VERSION: "3.2"
        BLENDER_VERSION: "3.3.6"
        BLENDER_MAJOR_MINOR: "3.3"
    command: flamenco-manager
    image: flamenco-manager:latest
    container_name: flamenco-manager
    volumes:
    # Mount the configuration file from the current directory
      - ./build/flamenco-manager.yaml:/flamenco/flamenco-manager.yaml
    ports:
      - "780:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v3/version"]
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 3