services:
  manager:
    build:
      context: .
      args:
        FLAMENCO_VERSION: "3.8.2"
        FLAMENCO_SHA256: "7a88e7fab8239cd626ba30b69019de1e5d058ad7f12260206b0f892c3e0f2de3"
        BLENDER_VERSION: "5.0.1"
        BLENDER_SHA256: "8019580ee1b7262e505f4196a00237ccf743c88d205b38d34201510676e60b09"
    image: flamenco:latest
    container_name: flamenco-manager
    restart: unless-stopped
    volumes:
      - ./build/flamenco-manager.yaml:/home/flamenco/flamenco-manager.yaml
    ports:
      - "780:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v3/version"]
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 3
